# -*- coding: utf-8 -*-
"""HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njZzQUax8Kugp1fTv04CTVyTDTGzY94l
"""

import tensorflow as tf


# Create a Constant op
hello = tf.constant('Hello, TensorFlow!')

# Start tf session
sess = tf.Session()

# Run the op
print(sess.run(hello))

